// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: configfiles.proto

#ifndef PROTOBUF_configfiles_2eproto__INCLUDED
#define PROTOBUF_configfiles_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3002000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3002000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace qiuwanli {
class MapFieldEntry;
class MapFieldEntryDefaultTypeInternal;
extern MapFieldEntryDefaultTypeInternal _MapFieldEntry_default_instance_;
class setfiles;
class setfilesDefaultTypeInternal;
extern setfilesDefaultTypeInternal _setfiles_default_instance_;
}  // namespace qiuwanli

namespace qiuwanli {

namespace protobuf_configfiles_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_configfiles_2eproto

// ===================================================================

class MapFieldEntry : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:qiuwanli.MapFieldEntry) */ {
 public:
  MapFieldEntry();
  virtual ~MapFieldEntry();

  MapFieldEntry(const MapFieldEntry& from);

  inline MapFieldEntry& operator=(const MapFieldEntry& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MapFieldEntry& default_instance();

  static inline const MapFieldEntry* internal_default_instance() {
    return reinterpret_cast<const MapFieldEntry*>(
               &_MapFieldEntry_default_instance_);
  }

  void Swap(MapFieldEntry* other);

  // implements Message ----------------------------------------------

  inline MapFieldEntry* New() const PROTOBUF_FINAL { return New(NULL); }

  MapFieldEntry* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const MapFieldEntry& from);
  void MergeFrom(const MapFieldEntry& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(MapFieldEntry* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string value = 2;
  void clear_value();
  static const int kValueFieldNumber = 2;
  const ::std::string& value() const;
  void set_value(const ::std::string& value);
  #if LANG_CXX11
  void set_value(::std::string&& value);
  #endif
  void set_value(const char* value);
  void set_value(const char* value, size_t size);
  ::std::string* mutable_value();
  ::std::string* release_value();
  void set_allocated_value(::std::string* value);

  // uint32 key = 1;
  void clear_key();
  static const int kKeyFieldNumber = 1;
  ::google::protobuf::uint32 key() const;
  void set_key(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:qiuwanli.MapFieldEntry)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr value_;
  ::google::protobuf::uint32 key_;
  mutable int _cached_size_;
  friend struct  protobuf_configfiles_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class setfiles : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:qiuwanli.setfiles) */ {
 public:
  setfiles();
  virtual ~setfiles();

  setfiles(const setfiles& from);

  inline setfiles& operator=(const setfiles& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const setfiles& default_instance();

  static inline const setfiles* internal_default_instance() {
    return reinterpret_cast<const setfiles*>(
               &_setfiles_default_instance_);
  }

  void Swap(setfiles* other);

  // implements Message ----------------------------------------------

  inline setfiles* New() const PROTOBUF_FINAL { return New(NULL); }

  setfiles* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const setfiles& from);
  void MergeFrom(const setfiles& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(setfiles* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .qiuwanli.MapFieldEntry map_field = 20;
  int map_field_size() const;
  void clear_map_field();
  static const int kMapFieldFieldNumber = 20;
  const ::qiuwanli::MapFieldEntry& map_field(int index) const;
  ::qiuwanli::MapFieldEntry* mutable_map_field(int index);
  ::qiuwanli::MapFieldEntry* add_map_field();
  ::google::protobuf::RepeatedPtrField< ::qiuwanli::MapFieldEntry >*
      mutable_map_field();
  const ::google::protobuf::RepeatedPtrField< ::qiuwanli::MapFieldEntry >&
      map_field() const;

  // @@protoc_insertion_point(class_scope:qiuwanli.setfiles)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::qiuwanli::MapFieldEntry > map_field_;
  mutable int _cached_size_;
  friend struct  protobuf_configfiles_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// MapFieldEntry

// uint32 key = 1;
inline void MapFieldEntry::clear_key() {
  key_ = 0u;
}
inline ::google::protobuf::uint32 MapFieldEntry::key() const {
  // @@protoc_insertion_point(field_get:qiuwanli.MapFieldEntry.key)
  return key_;
}
inline void MapFieldEntry::set_key(::google::protobuf::uint32 value) {
  
  key_ = value;
  // @@protoc_insertion_point(field_set:qiuwanli.MapFieldEntry.key)
}

// string value = 2;
inline void MapFieldEntry::clear_value() {
  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& MapFieldEntry::value() const {
  // @@protoc_insertion_point(field_get:qiuwanli.MapFieldEntry.value)
  return value_.GetNoArena();
}
inline void MapFieldEntry::set_value(const ::std::string& value) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:qiuwanli.MapFieldEntry.value)
}
#if LANG_CXX11
inline void MapFieldEntry::set_value(::std::string&& value) {
  
  value_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:qiuwanli.MapFieldEntry.value)
}
#endif
inline void MapFieldEntry::set_value(const char* value) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:qiuwanli.MapFieldEntry.value)
}
inline void MapFieldEntry::set_value(const char* value, size_t size) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:qiuwanli.MapFieldEntry.value)
}
inline ::std::string* MapFieldEntry::mutable_value() {
  
  // @@protoc_insertion_point(field_mutable:qiuwanli.MapFieldEntry.value)
  return value_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* MapFieldEntry::release_value() {
  // @@protoc_insertion_point(field_release:qiuwanli.MapFieldEntry.value)
  
  return value_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MapFieldEntry::set_allocated_value(::std::string* value) {
  if (value != NULL) {
    
  } else {
    
  }
  value_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set_allocated:qiuwanli.MapFieldEntry.value)
}

// -------------------------------------------------------------------

// setfiles

// repeated .qiuwanli.MapFieldEntry map_field = 20;
inline int setfiles::map_field_size() const {
  return map_field_.size();
}
inline void setfiles::clear_map_field() {
  map_field_.Clear();
}
inline const ::qiuwanli::MapFieldEntry& setfiles::map_field(int index) const {
  // @@protoc_insertion_point(field_get:qiuwanli.setfiles.map_field)
  return map_field_.Get(index);
}
inline ::qiuwanli::MapFieldEntry* setfiles::mutable_map_field(int index) {
  // @@protoc_insertion_point(field_mutable:qiuwanli.setfiles.map_field)
  return map_field_.Mutable(index);
}
inline ::qiuwanli::MapFieldEntry* setfiles::add_map_field() {
  // @@protoc_insertion_point(field_add:qiuwanli.setfiles.map_field)
  return map_field_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::qiuwanli::MapFieldEntry >*
setfiles::mutable_map_field() {
  // @@protoc_insertion_point(field_mutable_list:qiuwanli.setfiles.map_field)
  return &map_field_;
}
inline const ::google::protobuf::RepeatedPtrField< ::qiuwanli::MapFieldEntry >&
setfiles::map_field() const {
  // @@protoc_insertion_point(field_list:qiuwanli.setfiles.map_field)
  return map_field_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace qiuwanli

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_configfiles_2eproto__INCLUDED
