// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: configfiles.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "configfiles.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace qiuwanli {
class MapFieldEntryDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<MapFieldEntry> {
} _MapFieldEntry_default_instance_;
class setfilesDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<setfiles> {
} _setfiles_default_instance_;

namespace protobuf_configfiles_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[2];

}  // namespace

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MapFieldEntry, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MapFieldEntry, key_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MapFieldEntry, value_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(setfiles, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(setfiles, map_field_),
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, -1, sizeof(MapFieldEntry)},
  { 6, -1, sizeof(setfiles)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_MapFieldEntry_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_setfiles_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "configfiles.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

}  // namespace

void TableStruct::Shutdown() {
  _MapFieldEntry_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
  _setfiles_default_instance_.Shutdown();
  delete file_level_metadata[1].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _MapFieldEntry_default_instance_.DefaultConstruct();
  _setfiles_default_instance_.DefaultConstruct();
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\021configfiles.proto\022\010qiuwanli\"+\n\rMapFiel"
      "dEntry\022\013\n\003key\030\001 \001(\r\022\r\n\005value\030\002 \001(\t\"6\n\010se"
      "tfiles\022*\n\tmap_field\030\024 \003(\0132\027.qiuwanli.Map"
      "FieldEntryb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 138);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "configfiles.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_configfiles_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int MapFieldEntry::kKeyFieldNumber;
const int MapFieldEntry::kValueFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

MapFieldEntry::MapFieldEntry()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_configfiles_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:qiuwanli.MapFieldEntry)
}
MapFieldEntry::MapFieldEntry(const MapFieldEntry& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.value().size() > 0) {
    value_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.value_);
  }
  key_ = from.key_;
  // @@protoc_insertion_point(copy_constructor:qiuwanli.MapFieldEntry)
}

void MapFieldEntry::SharedCtor() {
  value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  key_ = 0u;
  _cached_size_ = 0;
}

MapFieldEntry::~MapFieldEntry() {
  // @@protoc_insertion_point(destructor:qiuwanli.MapFieldEntry)
  SharedDtor();
}

void MapFieldEntry::SharedDtor() {
  value_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void MapFieldEntry::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MapFieldEntry::descriptor() {
  protobuf_configfiles_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_configfiles_2eproto::file_level_metadata[0].descriptor;
}

const MapFieldEntry& MapFieldEntry::default_instance() {
  protobuf_configfiles_2eproto::InitDefaults();
  return *internal_default_instance();
}

MapFieldEntry* MapFieldEntry::New(::google::protobuf::Arena* arena) const {
  MapFieldEntry* n = new MapFieldEntry;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void MapFieldEntry::Clear() {
// @@protoc_insertion_point(message_clear_start:qiuwanli.MapFieldEntry)
  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  key_ = 0u;
}

bool MapFieldEntry::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:qiuwanli.MapFieldEntry)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint32 key = 1;
      case 1: {
        if (tag == 8u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &key_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string value = 2;
      case 2: {
        if (tag == 18u) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_value()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->value().data(), this->value().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "qiuwanli.MapFieldEntry.value"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:qiuwanli.MapFieldEntry)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:qiuwanli.MapFieldEntry)
  return false;
#undef DO_
}

void MapFieldEntry::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:qiuwanli.MapFieldEntry)
  // uint32 key = 1;
  if (this->key() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->key(), output);
  }

  // string value = 2;
  if (this->value().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->value().data(), this->value().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "qiuwanli.MapFieldEntry.value");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->value(), output);
  }

  // @@protoc_insertion_point(serialize_end:qiuwanli.MapFieldEntry)
}

::google::protobuf::uint8* MapFieldEntry::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:qiuwanli.MapFieldEntry)
  // uint32 key = 1;
  if (this->key() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->key(), target);
  }

  // string value = 2;
  if (this->value().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->value().data(), this->value().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "qiuwanli.MapFieldEntry.value");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->value(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:qiuwanli.MapFieldEntry)
  return target;
}

size_t MapFieldEntry::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:qiuwanli.MapFieldEntry)
  size_t total_size = 0;

  // string value = 2;
  if (this->value().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->value());
  }

  // uint32 key = 1;
  if (this->key() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->key());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MapFieldEntry::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:qiuwanli.MapFieldEntry)
  GOOGLE_DCHECK_NE(&from, this);
  const MapFieldEntry* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const MapFieldEntry>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:qiuwanli.MapFieldEntry)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:qiuwanli.MapFieldEntry)
    MergeFrom(*source);
  }
}

void MapFieldEntry::MergeFrom(const MapFieldEntry& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:qiuwanli.MapFieldEntry)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.value().size() > 0) {

    value_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.value_);
  }
  if (from.key() != 0) {
    set_key(from.key());
  }
}

void MapFieldEntry::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:qiuwanli.MapFieldEntry)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MapFieldEntry::CopyFrom(const MapFieldEntry& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:qiuwanli.MapFieldEntry)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MapFieldEntry::IsInitialized() const {
  return true;
}

void MapFieldEntry::Swap(MapFieldEntry* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MapFieldEntry::InternalSwap(MapFieldEntry* other) {
  value_.Swap(&other->value_);
  std::swap(key_, other->key_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata MapFieldEntry::GetMetadata() const {
  protobuf_configfiles_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_configfiles_2eproto::file_level_metadata[0];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// MapFieldEntry

// uint32 key = 1;
void MapFieldEntry::clear_key() {
  key_ = 0u;
}
::google::protobuf::uint32 MapFieldEntry::key() const {
  // @@protoc_insertion_point(field_get:qiuwanli.MapFieldEntry.key)
  return key_;
}
void MapFieldEntry::set_key(::google::protobuf::uint32 value) {
  
  key_ = value;
  // @@protoc_insertion_point(field_set:qiuwanli.MapFieldEntry.key)
}

// string value = 2;
void MapFieldEntry::clear_value() {
  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& MapFieldEntry::value() const {
  // @@protoc_insertion_point(field_get:qiuwanli.MapFieldEntry.value)
  return value_.GetNoArena();
}
void MapFieldEntry::set_value(const ::std::string& value) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:qiuwanli.MapFieldEntry.value)
}
#if LANG_CXX11
void MapFieldEntry::set_value(::std::string&& value) {
  
  value_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:qiuwanli.MapFieldEntry.value)
}
#endif
void MapFieldEntry::set_value(const char* value) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:qiuwanli.MapFieldEntry.value)
}
void MapFieldEntry::set_value(const char* value, size_t size) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:qiuwanli.MapFieldEntry.value)
}
::std::string* MapFieldEntry::mutable_value() {
  
  // @@protoc_insertion_point(field_mutable:qiuwanli.MapFieldEntry.value)
  return value_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* MapFieldEntry::release_value() {
  // @@protoc_insertion_point(field_release:qiuwanli.MapFieldEntry.value)
  
  return value_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void MapFieldEntry::set_allocated_value(::std::string* value) {
  if (value != NULL) {
    
  } else {
    
  }
  value_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set_allocated:qiuwanli.MapFieldEntry.value)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int setfiles::kMapFieldFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

setfiles::setfiles()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_configfiles_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:qiuwanli.setfiles)
}
setfiles::setfiles(const setfiles& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      map_field_(from.map_field_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:qiuwanli.setfiles)
}

void setfiles::SharedCtor() {
  _cached_size_ = 0;
}

setfiles::~setfiles() {
  // @@protoc_insertion_point(destructor:qiuwanli.setfiles)
  SharedDtor();
}

void setfiles::SharedDtor() {
}

void setfiles::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* setfiles::descriptor() {
  protobuf_configfiles_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_configfiles_2eproto::file_level_metadata[1].descriptor;
}

const setfiles& setfiles::default_instance() {
  protobuf_configfiles_2eproto::InitDefaults();
  return *internal_default_instance();
}

setfiles* setfiles::New(::google::protobuf::Arena* arena) const {
  setfiles* n = new setfiles;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void setfiles::Clear() {
// @@protoc_insertion_point(message_clear_start:qiuwanli.setfiles)
  map_field_.Clear();
}

bool setfiles::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:qiuwanli.setfiles)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(16383u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .qiuwanli.MapFieldEntry map_field = 20;
      case 20: {
        if (tag == 162u) {
          DO_(input->IncrementRecursionDepth());
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_map_field()));
        } else {
          goto handle_unusual;
        }
        input->UnsafeDecrementRecursionDepth();
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:qiuwanli.setfiles)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:qiuwanli.setfiles)
  return false;
#undef DO_
}

void setfiles::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:qiuwanli.setfiles)
  // repeated .qiuwanli.MapFieldEntry map_field = 20;
  for (unsigned int i = 0, n = this->map_field_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      20, this->map_field(i), output);
  }

  // @@protoc_insertion_point(serialize_end:qiuwanli.setfiles)
}

::google::protobuf::uint8* setfiles::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:qiuwanli.setfiles)
  // repeated .qiuwanli.MapFieldEntry map_field = 20;
  for (unsigned int i = 0, n = this->map_field_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        20, this->map_field(i), false, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:qiuwanli.setfiles)
  return target;
}

size_t setfiles::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:qiuwanli.setfiles)
  size_t total_size = 0;

  // repeated .qiuwanli.MapFieldEntry map_field = 20;
  {
    unsigned int count = this->map_field_size();
    total_size += 2UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->map_field(i));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void setfiles::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:qiuwanli.setfiles)
  GOOGLE_DCHECK_NE(&from, this);
  const setfiles* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const setfiles>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:qiuwanli.setfiles)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:qiuwanli.setfiles)
    MergeFrom(*source);
  }
}

void setfiles::MergeFrom(const setfiles& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:qiuwanli.setfiles)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  map_field_.MergeFrom(from.map_field_);
}

void setfiles::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:qiuwanli.setfiles)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void setfiles::CopyFrom(const setfiles& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:qiuwanli.setfiles)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool setfiles::IsInitialized() const {
  return true;
}

void setfiles::Swap(setfiles* other) {
  if (other == this) return;
  InternalSwap(other);
}
void setfiles::InternalSwap(setfiles* other) {
  map_field_.UnsafeArenaSwap(&other->map_field_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata setfiles::GetMetadata() const {
  protobuf_configfiles_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_configfiles_2eproto::file_level_metadata[1];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// setfiles

// repeated .qiuwanli.MapFieldEntry map_field = 20;
int setfiles::map_field_size() const {
  return map_field_.size();
}
void setfiles::clear_map_field() {
  map_field_.Clear();
}
const ::qiuwanli::MapFieldEntry& setfiles::map_field(int index) const {
  // @@protoc_insertion_point(field_get:qiuwanli.setfiles.map_field)
  return map_field_.Get(index);
}
::qiuwanli::MapFieldEntry* setfiles::mutable_map_field(int index) {
  // @@protoc_insertion_point(field_mutable:qiuwanli.setfiles.map_field)
  return map_field_.Mutable(index);
}
::qiuwanli::MapFieldEntry* setfiles::add_map_field() {
  // @@protoc_insertion_point(field_add:qiuwanli.setfiles.map_field)
  return map_field_.Add();
}
::google::protobuf::RepeatedPtrField< ::qiuwanli::MapFieldEntry >*
setfiles::mutable_map_field() {
  // @@protoc_insertion_point(field_mutable_list:qiuwanli.setfiles.map_field)
  return &map_field_;
}
const ::google::protobuf::RepeatedPtrField< ::qiuwanli::MapFieldEntry >&
setfiles::map_field() const {
  // @@protoc_insertion_point(field_list:qiuwanli.setfiles.map_field)
  return map_field_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace qiuwanli

// @@protoc_insertion_point(global_scope)
