// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fffff.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "fffff.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace qiuwanli {
class ConfigFileDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<ConfigFile> {
} _ConfigFile_default_instance_;

namespace protobuf_fffff_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[1];

}  // namespace

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ConfigFile, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ConfigFile, config_),
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, -1, sizeof(ConfigFile)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_ConfigFile_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "fffff.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

}  // namespace

void TableStruct::Shutdown() {
  _ConfigFile_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _ConfigFile_default_instance_.DefaultConstruct();
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\013fffff.proto\022\010qiuwanli\"\034\n\nConfigFile\022\016\n"
      "\006config\030\001 \003(\tb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 61);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "fffff.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_fffff_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ConfigFile::kConfigFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ConfigFile::ConfigFile()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_fffff_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:qiuwanli.ConfigFile)
}
ConfigFile::ConfigFile(const ConfigFile& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      config_(from.config_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:qiuwanli.ConfigFile)
}

void ConfigFile::SharedCtor() {
  _cached_size_ = 0;
}

ConfigFile::~ConfigFile() {
  // @@protoc_insertion_point(destructor:qiuwanli.ConfigFile)
  SharedDtor();
}

void ConfigFile::SharedDtor() {
}

void ConfigFile::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ConfigFile::descriptor() {
  protobuf_fffff_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_fffff_2eproto::file_level_metadata[0].descriptor;
}

const ConfigFile& ConfigFile::default_instance() {
  protobuf_fffff_2eproto::InitDefaults();
  return *internal_default_instance();
}

ConfigFile* ConfigFile::New(::google::protobuf::Arena* arena) const {
  ConfigFile* n = new ConfigFile;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ConfigFile::Clear() {
// @@protoc_insertion_point(message_clear_start:qiuwanli.ConfigFile)
  config_.Clear();
}

bool ConfigFile::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:qiuwanli.ConfigFile)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated string config = 1;
      case 1: {
        if (tag == 10u) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_config()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->config(this->config_size() - 1).data(),
            this->config(this->config_size() - 1).length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "qiuwanli.ConfigFile.config"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:qiuwanli.ConfigFile)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:qiuwanli.ConfigFile)
  return false;
#undef DO_
}

void ConfigFile::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:qiuwanli.ConfigFile)
  // repeated string config = 1;
  for (int i = 0; i < this->config_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->config(i).data(), this->config(i).length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "qiuwanli.ConfigFile.config");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->config(i), output);
  }

  // @@protoc_insertion_point(serialize_end:qiuwanli.ConfigFile)
}

::google::protobuf::uint8* ConfigFile::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:qiuwanli.ConfigFile)
  // repeated string config = 1;
  for (int i = 0; i < this->config_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->config(i).data(), this->config(i).length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "qiuwanli.ConfigFile.config");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(1, this->config(i), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:qiuwanli.ConfigFile)
  return target;
}

size_t ConfigFile::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:qiuwanli.ConfigFile)
  size_t total_size = 0;

  // repeated string config = 1;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->config_size());
  for (int i = 0; i < this->config_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->config(i));
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ConfigFile::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:qiuwanli.ConfigFile)
  GOOGLE_DCHECK_NE(&from, this);
  const ConfigFile* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ConfigFile>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:qiuwanli.ConfigFile)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:qiuwanli.ConfigFile)
    MergeFrom(*source);
  }
}

void ConfigFile::MergeFrom(const ConfigFile& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:qiuwanli.ConfigFile)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  config_.MergeFrom(from.config_);
}

void ConfigFile::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:qiuwanli.ConfigFile)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ConfigFile::CopyFrom(const ConfigFile& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:qiuwanli.ConfigFile)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ConfigFile::IsInitialized() const {
  return true;
}

void ConfigFile::Swap(ConfigFile* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ConfigFile::InternalSwap(ConfigFile* other) {
  config_.UnsafeArenaSwap(&other->config_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ConfigFile::GetMetadata() const {
  protobuf_fffff_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_fffff_2eproto::file_level_metadata[0];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// ConfigFile

// repeated string config = 1;
int ConfigFile::config_size() const {
  return config_.size();
}
void ConfigFile::clear_config() {
  config_.Clear();
}
const ::std::string& ConfigFile::config(int index) const {
  // @@protoc_insertion_point(field_get:qiuwanli.ConfigFile.config)
  return config_.Get(index);
}
::std::string* ConfigFile::mutable_config(int index) {
  // @@protoc_insertion_point(field_mutable:qiuwanli.ConfigFile.config)
  return config_.Mutable(index);
}
void ConfigFile::set_config(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:qiuwanli.ConfigFile.config)
  config_.Mutable(index)->assign(value);
}
void ConfigFile::set_config(int index, const char* value) {
  config_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:qiuwanli.ConfigFile.config)
}
void ConfigFile::set_config(int index, const char* value, size_t size) {
  config_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:qiuwanli.ConfigFile.config)
}
::std::string* ConfigFile::add_config() {
  // @@protoc_insertion_point(field_add_mutable:qiuwanli.ConfigFile.config)
  return config_.Add();
}
void ConfigFile::add_config(const ::std::string& value) {
  config_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:qiuwanli.ConfigFile.config)
}
void ConfigFile::add_config(const char* value) {
  config_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:qiuwanli.ConfigFile.config)
}
void ConfigFile::add_config(const char* value, size_t size) {
  config_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:qiuwanli.ConfigFile.config)
}
const ::google::protobuf::RepeatedPtrField< ::std::string>&
ConfigFile::config() const {
  // @@protoc_insertion_point(field_list:qiuwanli.ConfigFile.config)
  return config_;
}
::google::protobuf::RepeatedPtrField< ::std::string>*
ConfigFile::mutable_config() {
  // @@protoc_insertion_point(field_mutable_list:qiuwanli.ConfigFile.config)
  return &config_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace qiuwanli

// @@protoc_insertion_point(global_scope)
